name: BADOL-BOT-V5 ULTIMATE CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install System Dependencies (For Canvas & SQLite3)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24.x

    - name: Install Dependencies
      run: |
        npm install

    # সিক্রেট থেকে ফাইল বানানোর ধাপটা পুরো বাদ, কারণ ফাইল এখন আপনার কোডেই আছে!

    - name: Start BADOL-BOT V5
      run: npm start
